/**
 * Candidate Types for Parallel Improvement Validation
 *
 * When users click an improvement card, we validate 3-5 candidate options
 * in parallel using PoB and show the top 3 to the user.
 *
 * Candidates are generated during initial analysis (descriptions only),
 * then validated on-demand when user clicks a card.
 */

import type { PathwayType } from './pathway';
import type { StatRequirement, TradeItemConstraints } from './TradeSearchInstruction';

// =============================================================================
// Candidate Types
// =============================================================================

/**
 * Validation status for a candidate option.
 * - 'pending': Not yet validated (waiting for user click)
 * - 'validating': Currently being validated with PoB
 * - 'validated': Successfully validated, results available
 * - 'failed': Validation attempted but failed (API error, invalid data)
 */
export type CandidateValidationStatus = 'pending' | 'validating' | 'validated' | 'failed';

/**
 * Actual stat delta from PoB validation.
 * Populated after validation completes.
 */
export interface CandidateStatDelta {
  /** DPS change as percentage (e.g., 15.5 means +15.5%) */
  dpsPercent: number;
  /** EHP change as percentage */
  ehpPercent: number;
  /** Absolute DPS change (optional, for display) */
  dpsAbsolute?: number;
  /** Absolute EHP change (optional, for display) */
  ehpAbsolute?: number;
  /** Life change as percentage (optional) */
  lifePercent?: number;
  /** Energy Shield change as percentage (optional) */
  esPercent?: number;
}

/**
 * Gem change specification for Skills pathway candidates.
 * Describes a gem swap or addition within a socket group.
 */
export interface CandidateGemChange {
  /** Socket group index (1-based) */
  socketGroupIndex: number;
  /** Socket group slot name (e.g., "Weapon 1", "Body Armour") */
  socketGroupSlot?: string;
  /** Gem to remove (null if only adding) */
  removeGem: string | null;
  /** Gem to add (null if only removing) */
  addGem: string | null;
  /** Level for the new gem (default: 20) */
  level?: number;
  /** Quality for the new gem (default: 20) */
  quality?: number;
}

/**
 * Trade search specification for Gear pathway candidates.
 * Describes a set of mods to search for on the trade site.
 */
export interface CandidateTradeSpec {
  /** Stats to search for with Trade API IDs */
  stats: StatRequirement[];
  /** Item constraints (base type, influences, etc.) */
  constraints?: TradeItemConstraints;
  /** Human-readable description of this search strategy */
  strategyDescription?: string;
}

/**
 * A single candidate option for an improvement.
 *
 * Generated by LLM during initial analysis (description fields only).
 * PoB validation populates actualDelta, isUpgrade, etc. on user click.
 */
export interface ImprovementCandidate {
  /** Unique identifier within this improvement (e.g., "brutality-swap", "strategy-a") */
  id: string;

  /** Short title describing this option (e.g., "Swap to Brutality Support") */
  title: string;

  /** Brief explanation of why this option might be good */
  rationale: string;

  /** Estimated impact before PoB validation (e.g., "~15% more damage") */
  estimatedImpact?: string;

  /** Trade-off description if applicable (e.g., "Loses elemental damage") */
  tradeoff?: string;

  /** Cost estimate (e.g., "~50c", "3 passive points", "free") */
  estimatedCost?: string;

  // === Domain-Specific Action Data ===

  /**
   * Skills pathway: gem change specification.
   * Contains socket group, gem to remove, gem to add.
   */
  gemChange?: CandidateGemChange;

  /**
   * Tree pathway: node IDs to allocate.
   * Array of passive tree node IDs.
   */
  nodeIds?: number[];

  /**
   * Tree pathway: node names for display.
   * Human-readable names corresponding to nodeIds.
   */
  nodeNames?: string[];

  /**
   * Gear pathway: trade search specification.
   * Describes the search strategy for this candidate.
   */
  tradeSpec?: CandidateTradeSpec;

  // === Validation Results (populated after PoB validation) ===

  /**
   * Current validation status.
   * @default 'pending'
   */
  validationStatus: CandidateValidationStatus;

  /**
   * Actual stat changes from PoB simulation.
   * Only populated when validationStatus is 'validated'.
   */
  actualDelta?: CandidateStatDelta;

  /**
   * Whether this candidate is an overall upgrade.
   * True if primary metric (DPS for offensive, EHP for defensive) improves
   * without significant regression in the other.
   */
  isUpgrade?: boolean;

  /**
   * Whether this candidate has mixed impact (some stats up, some down).
   * When true, UI should show a warning that this is a tradeoff.
   */
  hasMixedImpact?: boolean;

  /**
   * Error message if validation failed.
   * Only populated when validationStatus is 'failed'.
   */
  validationError?: string;

  /**
   * Ranking score after validation.
   * Used to sort candidates. Higher = better.
   * Score = dpsPercent * dpsWeight + ehpPercent * ehpWeight
   */
  score?: number;
}

// =============================================================================
// Candidate Set Types
// =============================================================================

/**
 * A complete set of validated candidates for an improvement.
 * Returned after parallel validation completes.
 */
export interface ValidatedCandidateSet {
  /** ID of the improvement these candidates are for */
  improvementId: string;

  /** Pathway type for context */
  pathway: PathwayType;

  /** All candidates after validation (sorted by score, best first) */
  candidates: ImprovementCandidate[];

  /** The best candidate (first in sorted list, convenience accessor) */
  bestCandidate: ImprovementCandidate | null;

  /** Number of candidates that are valid upgrades */
  upgradeCount: number;

  /** Total validation time in milliseconds */
  validationTimeMs: number;

  /** Timestamp when validation completed */
  validatedAt: number;
}

// =============================================================================
// Validation Request/Response Types
// =============================================================================

/**
 * Request to validate candidates for an improvement.
 */
export interface ValidateCandidatesRequest {
  /** Build ID */
  buildId: string;

  /** Improvement ID */
  improvementId: string;

  /** Candidates to validate (from improvement.candidates) */
  candidates: ImprovementCandidate[];

  /** Pathway type (determines validation method) */
  pathway: PathwayType;

  /** Optional ranking weights (defaults based on improvement category) */
  weights?: CandidateRankingWeights;
}

/**
 * Weights for ranking candidates after validation.
 * Score = dpsPercent * dps + ehpPercent * ehp
 */
export interface CandidateRankingWeights {
  /** Weight for DPS improvement (0-1) */
  dps: number;
  /** Weight for EHP improvement (0-1) */
  ehp: number;
}

/**
 * Default ranking weights by improvement category.
 */
export const DEFAULT_RANKING_WEIGHTS: Record<string, CandidateRankingWeights> = {
  offensive: { dps: 0.8, ehp: 0.2 },
  defensive: { dps: 0.2, ehp: 0.8 },
  utility: { dps: 0.5, ehp: 0.5 },
  // Fallback for unknown categories
  default: { dps: 0.5, ehp: 0.5 },
};

/**
 * Response from candidate validation endpoint.
 */
export interface ValidateCandidatesResponse {
  /** Whether validation completed successfully */
  success: boolean;

  /** Validated candidate set (if success) */
  result?: ValidatedCandidateSet;

  /** Error message (if failed) */
  error?: string;
}

// =============================================================================
// Multi-Strategy Trade Types
// =============================================================================

/**
 * A single trade search strategy for multi-strategy search.
 * Each strategy represents a different approach to finding items.
 */
export interface TradeSearchStrategy {
  /** Unique identifier for this strategy */
  strategyId: string;

  /** Human-readable name (e.g., "High Life + Resistances") */
  name: string;

  /** LLM reasoning for why this strategy might work */
  reasoning: string;

  /** Priority order (1 = highest priority, tried first) */
  priority: number;

  /** The stats to search for in this strategy */
  stats: StatRequirement[];

  /** Item constraints for this strategy */
  constraints?: TradeItemConstraints;
}

/**
 * Progress update for a single strategy during multi-strategy search.
 */
export interface StrategyProgress {
  /** Strategy ID */
  strategyId: string;

  /** Strategy name for display */
  strategyName: string;

  /** Current status */
  status: 'pending' | 'searching' | 'iterating' | 'complete' | 'failed';

  /** Current iteration (if iterating) */
  iteration?: number;

  /** Number of results found so far */
  resultCount?: number;

  /** Minimum price found so far */
  minPrice?: number;

  /** Trade URL (if results found) */
  tradeUrl?: string;

  /** Error message (if failed) */
  error?: string;
}

/**
 * Overall progress for multi-strategy search.
 */
export interface MultiStrategyProgress {
  /** Total number of strategies */
  totalStrategies: number;

  /** Number of completed strategies */
  completedStrategies: number;

  /** Currently executing strategy name */
  currentStrategy?: string;

  /** Current phase */
  phase: 'initializing' | 'searching' | 'comparing' | 'validating' | 'complete';

  /** Per-strategy progress */
  strategies: StrategyProgress[];
}

/**
 * Result from a single strategy after search completes.
 */
export interface StrategyResult {
  /** Strategy ID */
  strategyId: string;

  /** Strategy name */
  strategyName: string;

  /** Number of items found */
  totalFound: number;

  /** Number of iterations performed */
  iterations: number;

  /** Best (lowest) price found */
  bestPrice: number | null;

  /** Trade URL for this strategy's search */
  tradeUrl: string | null;

  /** Top items from this strategy */
  items: TradeResultItem[];
}

/**
 * A single item from trade search results.
 */
export interface TradeResultItem {
  /** Item name */
  name: string;

  /** Base type */
  baseType: string;

  /** Price */
  price: {
    amount: number;
    currency: string;
  };

  /** Trade listing ID */
  listingId: string;

  /** Which strategy found this item */
  strategyId: string;

  /** Stats on the item */
  stats?: Array<{
    id: string;
    value: number;
    displayName?: string;
  }>;

  /** PoB validation result (if validated) */
  pobValidation?: {
    dpsChange: number;
    ehpChange: number;
    canEquip: boolean;
  };

  /** Efficiency score: weighted stats / price */
  efficiencyScore?: number;
}

/**
 * Compared results across all strategies.
 */
export interface MultiStrategyComparedResult {
  /** Best overall item considering all factors */
  bestOverall: TradeResultItem | null;

  /** Best item from each strategy */
  perStrategy: Record<string, TradeResultItem | null>;

  /** Non-obvious finds (items from lower-priority strategies that are actually good) */
  surprisingFinds: TradeResultItem[];

  /** Summary of trade-offs between strategies */
  tradeOffSummary: string[];

  /** All results for reference */
  allResults: StrategyResult[];
}
