/**
 * OptimizationKBModule - Structured data from ladder-sourced KB optimization modules
 *
 * These modules are generated by `scripts/kb-generator/optimization-kb-generator.ts`
 * from poe.ninja ladder data with PoB validation. They provide aggregated patterns
 * from successful builds to guide optimization.
 *
 * The data is used by `/optimize-build` and `/create-build-guide` commands to:
 * 1. Set L100 benchmark targets (DPS, EHP)
 * 2. Prioritize keystones/notables with high ladder usage
 * 3. Guide gear selection based on ladder patterns
 * 4. Recommend aura setups from meta builds
 */

/**
 * Tier breakdown for sample segmentation
 */
export interface TierBreakdown {
  elite: number;
  high: number;
  mid: number;
  entry: number;
}

/**
 * Stat benchmarks by tier
 */
export interface TierBenchmarks {
  tier: 'elite' | 'high' | 'mid' | 'entry';
  dps: {
    min: number;
    median: number;
    max: number;
  };
  ehp: {
    min: number;
    median: number;
    max: number;
  };
  life: number;
  eleRes: string; // e.g., "90%"
  chaosRes: string; // e.g., "75%"
}

/**
 * Keystone usage pattern from ladder
 */
export interface KeystonePattern {
  name: string;
  usage: number; // 0-100 percentage
  tierTrend: 'Elite-heavy' | 'Entry-heavy' | 'Balanced';
  notes?: string;
}

/**
 * Notable usage pattern from ladder
 */
export interface NotablePattern {
  name: string;
  usage: number; // 0-100 percentage
}

/**
 * Gear slot pattern from ladder
 */
export interface GearSlotPattern {
  slot: string;
  uniquePercent: number; // % of builds using unique in this slot
  rarePercent: number;
  uniques: Array<{
    name: string;
    baseType: string;
    usage: number; // 0-100 percentage
    tierTrend: 'Elite-heavy' | 'Entry-heavy' | 'Balanced';
  }>;
}

/**
 * Aura usage pattern from ladder
 */
export interface AuraPattern {
  name: string;
  usage: number; // 0-100 percentage
  dominantTier: 'Elite' | 'High' | 'Mid' | 'Entry';
}

/**
 * Main skill support gem pattern
 */
export interface MainSkillSetup {
  mainSkill: string;
  supports: Array<{
    name: string;
    usage: number;
    avgLevel?: number;
    notes?: string;
  }>;
  alternatives: Array<{
    mainSkill: string;
    supports: string[];
    usage: number;
  }>;
}

/**
 * Node pairing pattern (commonly taken together)
 */
export interface NodePairing {
  nodes: string[];
  usage: number;
  purpose: string;
}

/**
 * Rare mod pattern from ladder builds
 */
export interface RareModPattern {
  mod: string;           // e.g., "+# to maximum Life"
  slot: string;          // e.g., "Helmet", "Gloves", "Boots"
  usage: number;         // Usage percentage (e.g., 87)
  tierGroup?: 'top-dps' | 'top-ehp' | 'balanced' | 'overall';  // Which build tier uses this
  modType?: 'explicit' | 'eldritch' | 'influenced' | 'implicit';  // Mod category
  vsOverall?: number;    // Differential vs overall usage (e.g., +46 means 46% more than overall)
}

/**
 * Item impact analysis showing stat deltas with vs without each unique
 */
export interface ItemImpactPattern {
  item: string;          // Item name (e.g., "Cloak of Flame")
  slot: string;          // Slot (e.g., "Body Armour")
  usage: number;         // Usage percentage
  physMaxHit?: number;   // Physical max hit (absolute)
  physMaxHitDelta?: number; // Delta percentage vs builds without (e.g., +50%)
  fireEhp?: number;      // Fire EHP
  totalEhp?: number;     // Total EHP
  totalEhpDelta?: number;// Delta percentage vs builds without
  dps?: number;          // DPS
  dpsDelta?: number;     // Delta percentage vs builds without
}

/**
 * Support gem impact analysis
 */
export interface SupportImpactPattern {
  support: string;       // Support gem name
  usage: number;         // Usage percentage
  dpsImpact?: number;    // DPS with support (absolute)
  dpsDelta?: number;     // DPS delta percentage
  ehpImpact?: number;    // EHP with support
  ehpDelta?: number;     // EHP delta percentage
}

/**
 * Keystone impact analysis
 */
export interface KeystoneImpactPattern {
  keystone: string;      // Keystone name
  usage: number;         // Usage percentage
  physMaxHit?: number;   // Physical max hit
  physMaxHitDelta?: number;
  totalEhp?: number;
  totalEhpDelta?: number;
  dps?: number;
  dpsDelta?: number;
  life?: number;
  lifeDelta?: number;
}

/**
 * Aura impact analysis
 */
export interface AuraImpactPattern {
  aura: string;          // Aura name
  usage: number;         // Usage percentage
  dpsImpact?: number;
  dpsDelta?: number;
  ehpImpact?: number;
  ehpDelta?: number;
  physMaxHit?: number;
  physMaxHitDelta?: number;
}

/**
 * Notable passive impact analysis
 */
export interface NotableImpactPattern {
  notable: string;       // Notable name
  usage: number;         // Usage percentage
  dpsImpact?: number;
  dpsDelta?: number;
  ehpImpact?: number;
  ehpDelta?: number;
}

/**
 * Flask usage pattern (if available)
 */
export interface FlaskPattern {
  name: string;          // Flask name
  slot?: number;         // Flask slot (1-5)
  usage: number;         // Usage percentage
  isUnique: boolean;     // Whether it's a unique flask
}

/**
 * Jewel usage pattern (if available)
 */
export interface JewelPattern {
  name: string;          // Jewel name
  type: 'unique' | 'rare' | 'cluster' | 'timeless' | 'abyss';
  usage: number;         // Usage percentage
  notes?: string;        // Additional context
}

/**
 * Complete optimization KB module structure
 */
export interface OptimizationKBModule {
  /**
   * Module identifier (e.g., "builds/chieftain-righteous-fire")
   */
  id: string;

  /**
   * Module type identifier
   */
  type: 'build-optimization-kb';

  /**
   * KB format version
   */
  format: 'ladder-v3';

  /**
   * When this module was generated
   */
  generated: string; // ISO date

  /**
   * Data source description
   */
  source: string;

  /**
   * League this data is from
   */
  league: string;

  /**
   * Number of builds analyzed
   */
  sampleSize: number;

  /**
   * Breakdown of builds by tier
   */
  tierBreakdown: TierBreakdown;

  /**
   * Optimization priority order (1 = highest priority)
   */
  optimizationPriority: string[];

  /**
   * Benchmarks by tier
   */
  benchmarks: TierBenchmarks[];

  /**
   * Keystone patterns
   */
  keystones: KeystonePattern[];

  /**
   * Notable patterns (>5% usage)
   */
  notables: NotablePattern[];

  /**
   * Common node pairings
   */
  nodePairings: NodePairing[];

  /**
   * Rare mod patterns from ladder builds
   */
  rareMods: RareModPattern[];

  /**
   * Main skill setup with supports
   */
  mainSkillSetup: MainSkillSetup;

  /**
   * Aura patterns
   */
  auras: AuraPattern[];

  /**
   * Gear patterns by slot
   */
  gearPatterns: GearSlotPattern[];

  /**
   * Gap analysis checklist items
   */
  gapAnalysisChecklist: string[];

  /**
   * Item impact analysis (optional - from Build Tier Analysis)
   */
  itemImpacts?: ItemImpactPattern[];

  /**
   * Support gem impact analysis (optional)
   */
  supportImpacts?: SupportImpactPattern[];

  /**
   * Keystone impact analysis (optional)
   */
  keystoneImpacts?: KeystoneImpactPattern[];

  /**
   * Aura impact analysis (optional)
   */
  auraImpacts?: AuraImpactPattern[];

  /**
   * Notable passive impact analysis (optional)
   */
  notableImpacts?: NotableImpactPattern[];

  /**
   * Flask patterns (optional - if flask section exists)
   */
  flasks?: FlaskPattern[];

  /**
   * Jewel patterns (optional - if jewel section exists)
   */
  jewels?: JewelPattern[];
}

/**
 * Parsed result from loading an optimization KB module
 */
export interface OptimizationKBLoadResult {
  /**
   * The parsed module, or null if not found/invalid
   */
  module: OptimizationKBModule | null;

  /**
   * Path to the source file
   */
  filePath: string;

  /**
   * Whether the file was found
   */
  found: boolean;

  /**
   * Parse errors if any
   */
  errors: string[];
}

/**
 * Context for optimization subagents derived from KB module
 */
export interface OptimizationKBContext {
  /**
   * Target benchmarks for optimization (typically 'mid' tier)
   */
  benchmarks: TierBenchmarks;

  /**
   * High-priority keystones (>50% usage)
   */
  priorityKeystones: KeystonePattern[];

  /**
   * High-priority notables (>50% usage)
   */
  priorityNotables: NotablePattern[];

  /**
   * Recommended gear patterns
   */
  gearPatterns: GearSlotPattern[];

  /**
   * Recommended aura setup (>50% usage)
   */
  priorityAuras: AuraPattern[];

  /**
   * Main skill support recommendations
   */
  mainSkillSupports: MainSkillSetup['supports'];

  /**
   * Source KB module metadata
   */
  source: {
    league: string;
    sampleSize: number;
    generated: string;
  };
}
